Myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('firstapp/', include('firstapp.urls')),
    path('carbone/', include('carboneapp.urls'))
]

carboneapp/urls.py
from django.urls import path
from .views import home, login_view, logout_view, questionnaire_energie

app_name = 'carboneapp'

urlpatterns = [
    path('home/', home, name='home'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('energy-form', questionnaire_energie, name='energy_form')
]

firstapp/urls.py
from django.urls import path
from .views import home, list_articles, details_article

app_name = 'firstapp'

urlpatterns = [
    path('home/', home, name='home'),
    path('article/', list_articles, name='articles'),
    path('article/detail_article_<int:id_article>', details_article, name='details')
]

carboneapp/models.py
from django.db import models
from django.contrib.auth.models import User

class QuestionnaireEnergie(models.Model):
    organisation_loue = models.BooleanField(verbose_name="Est-ce que votre organisation loue le site à un tiers ?")
    achat_electricite = models.PositiveIntegerField(verbose_name="Achat d'électricité (KWh)")
    surface_climatisee = models.PositiveIntegerField(verbose_name="Surface climatisée (m²)")
    nombre_employes_dechet = models.PositiveIntegerField(verbose_name="Déchets (Renseigner le nombre total d'employes qui travaillent dans l'entite (ETP))")
    nombre_employes_eau = models.PositiveIntegerField(verbose_name="Eau (Renseigner le nombre total d'employes qui travaillent dans l'entite (ETP))")
    cout_renovation = models.PositiveIntegerField(null=True, blank=True, verbose_name="Coût total des travaux de rénovation")
    entite = models.OneToOneField(User, on_delete=models.CASCADE, related_name='QuestEnergy')

    def __str__(self):
        return f"Questionnaire Energie"

class DeplacementsProfessionnels(models.Model):
    cout_avion = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Coût déplacement avion")
    cout_taxi_voiture = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Coût déplacement taxi/voiture")
    cout_train = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Coût déplacement train")
    cout_bus_metro_tramway = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Coût déplacement bus/métro/tramway")
    cout_bateau = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Coût déplacement bateau")
    entite = models.OneToOneField(User, on_delete=models.CASCADE, related_name='DeplacementProfessionnel')
    def __str__(self):
        return "Déplacements professionnels"

class Vehicule(models.Model):
    site = models.CharField(max_length=255, verbose_name="Site")
    description = models.TextField(verbose_name="Description")
    type_motorisation = models.CharField(max_length=255, verbose_name="Type de motorisation")
    masse_vehicule = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Masse du véhicule (kg)")
    annee_immatriculation = models.PositiveIntegerField(verbose_name="Année d'immatriculation")
    distance_annuelle = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Distance annuelle (km)")
    type_carburant = models.CharField(max_length=255, verbose_name="Type de carburant")
    consommation_carburant = models.DecimalField(max_digits=10, decimal_places=2,
                                                 verbose_name="Consommation de carburant (l)")
    entite = models.ForeignKey(User, on_delete=models.CASCADE, related_name='Vehicule')

    def __str__(self):
        return f"{self.type_motorisation} - {self.description}"

class TrajetDomicileTravail(models.Model):
    cout_voiture = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Coût trajet voiture")
    cout_train = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Coût trajet train")
    cout_bus_metro_tramway = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Coût trajet bus/métro/tramway")
    cout_autres = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Coût trajet autres")
    entite = models.OneToOneField(User, on_delete=models.CASCADE, related_name='TrajetDomicileTravail')
    def __str__(self):
        return "Trajet domicile-travail"

carboneapp/forms.py
from django import forms
from .models import QuestionnaireEnergie

class QuestionnaireEnergieForm(forms.ModelForm):
    class Meta:
        model = QuestionnaireEnergie
        fields = ['organisation_loue', 'achat_electricite', 'surface_climatisee',
                  'nombre_employes_dechet', 'nombre_employes_eau', 'cout_renovation']

carboneapp/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import QuestionnaireEnergieForm
from .models import QuestionnaireEnergie
from .utils import group_required
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied


def profile_required(view_func):
    def wrapper(request, *args, **kwargs):
        if request.user.groups.filter(name="user_carbon").exists():
            return view_func(request, *args, **kwargs)
        raise PermissionDenied
    return wrapper

@login_required
@group_required('user_carbone')
def home(request):

    return render(request, 'carboneapp/home.html')

def login_view(request):

    if 'login_submit' in request.POST:
        email = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=email, password=password)

        if user is not None:
            login(request, user)
            return redirect('carboneapp:home')
        else:
            messages.error(request, 'User introuvable')
    return render(request, 'carboneapp/login.html')


def logout_view(request):
    logout(request)

    return redirect('carboneapp:login')

@login_required
@profile_required
def questionnaire_energie(request):
    energy_model = QuestionnaireEnergie.objects.filter(entite=request.user).first()

    if request.method == 'POST':
        form = QuestionnaireEnergieForm(request.POST, instance=energy_model)
        if form.is_valid():
            form_ = form.save(commit=False)
            form_.entite = request.user
            form_.save()
            messages.success(request, 'Le questionnaire ernergy est enregistré avec succès.')
            return HttpResponseRedirect(reverse('carboneapp:energy_form'))
    else:
        form = QuestionnaireEnergieForm(instance=energy_model)

    return render(request, 'carboneapp/energy_form.html', context={'form': form})

templates/carboneapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/carbonestyle.css' %}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <title>{% block title %}Titre de la page{% endblock %}</title>
    <!--link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"-->
</head>
<body>
    <div class="container">
        <header>
            <div id="branding">
                <h1><span class="highlight">Bilan</span> Carbonne - {{ request.user.username }}</h1>
            </div>
            <nav>
                <ul>
                    <li><a href="{% url 'carboneapp:home' %}">Accueil</a></li>
                    {% if request.user.is_authenticated %}
                        <li><a href="{% url 'carboneapp:logout' %}">Deconnexion</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>

        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}

        <section id="content">

            {% block content %}
            {% endblock %}
        </section>

        <footer>
            <p>Enquête caronne 2024</p>
        </footer>
    </div>
</body>
</html>

templates/carboneapp/energy_form.html
{% extends 'carboneapp/base.html'%}

{% block title %}Energy-form{% endblock %}

{% block content %}
    <h3>Questionnaire energie</h3>
    <form method="post" class="energy-form">
        {% csrf_token %}
        <div class="form-group">
            {{ form.as_p }}
        </div>

        <button type="submit">Soumettre</button>

    </form>
{% endblock %}

templates/carboneapp/home.html
{% extends "carboneapp/base.html" %}

{% block title %}
    Accueil
{% endblock %}

{% block content %}
    <h2>Bienvenue sur la plateforme dédié à ...</h2>
    <p style="text-align: center">Veuillez selectionner un questionnaire pour commencer.</p>

    <ul>
        <li>
            <a href="{% url 'carboneapp:energy_form' %}"><i class="fas fa-lightbulb"></i> Consommation d'Énergie</a>
            <p>Ce questionnaire concerne votre consommation d'électricité, de gaz, de chauffage, etc.</p>
        </li>
        <li>
            <a href="#"><i class="fas fa-car"></i> Déplacement/Transports</a>
            <p>Ce questionnaire concerne les déplacements de vos employés, l'utilisation de véhicules d'entreprise, etc.</p>
        </li>
        <li>
            <a href="#"><i class="fas fa-trash"></i> Gestion des Déchets</a>
            <p>Ce questionnaire concerne la production, le tri et le traitement de vos déchets.</p>
        </li>
        <li>
            <a href="#"><i class="fas fa-shopping-cart"></i> Achats et Locations</a>
            <p>Ce questionnaire concerne l'impact carbone des produits et services que vous achetez.</p>
        </li>
    </ul>
{% endblock %}

templates/carboneapp/login.html
{% extends 'carboneapp/base.html'%}

{% block title %}Login{% endblock %}

{% block content %}
    <div class="login-container">
        <h2>Connexion</h2>
        <form method="post" class="form-group">
            {% csrf_token %}
            <label for="username" class="form-label">Email</label>
            <input type="text" id="username" name="username" required>
            <label for="password" class="form-label">Password</label>
            <input type="password" id="password" name="password" required>
            <input type="submit" name="login_submit" class="form-button">
        </form>
    </div>
{% endblock%}