Myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('firstapp/', include('firstapp.urls')),
    path('carbone/', include('carboneapp.urls'))
]

firstapp/urls.py
from django.urls import path
from .views import home, list_articles, details_article

app_name = 'firstapp'

urlpatterns = [
    path('home/', home, name='home'),
    path('article/', list_articles, name='articles'),
    path('article/detail_article_<int:id_article>', details_article, name='details')
]

firstapp/models.py
from django.db import models
from django.utils.timezone import now

class Auteur(models.Model):
    prenom = models.CharField(max_length=100)
    nom = models.CharField(max_length=100)
    profession = models.CharField(max_length=100)
    age = models.IntegerField()
    #articles = models.ForeignKey(Article ...)
    def __str__(self):
        return self.prenom

class Article(models.Model):
    titre = models.CharField(max_length=255)
    contenu = models.TextField() # Text long
    date_publication = models.DateTimeField(default=now)
    auteur = models.ForeignKey(Auteur, on_delete=models.CASCADE, related_name='articles')

    def __str__(self):
        return self.titre

firstapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Article, Auteur

# Create your views here.

def home(request):
    return HttpResponse('<h1>Hello Word !!!</h1>')


def list_articles(request):

    articles = Article.objects.all()
    auteurs = Auteur.objects.all()

    try:
        if request.session['auteur_selected'] is not None:
            articles_filtre = Article.objects.filter(auteur=Auteur.objects.get(id=request.session['auteur_selected']))
    except:
        articles_filtre = None

    if 'listes_auteur' in request.POST:
        request.session['auteur_selected'] = int(request.POST.get('listes_auteur'))
        articles_filtre = Article.objects.filter(auteur=Auteur.objects.get(id=request.session['auteur_selected']))

    context = {'articles': articles, 'auteurs': auteurs, 'articles_filtre': articles_filtre}

    return render(request, 'firstapp/articles.html', context=context)

def details_article(request, id_article):

    #article = Article.objects.get(id=id_article)
    article = get_object_or_404(Article, id=id_article)
    context = {'art': article}
    return render(request, 'firstapp/details_articles.html', context=context)

templates/firstapp/articles.html
{% extends "firstapp/base.html" %}
{% block title %}Accueil{% endblock %}
{% block content %}
    <h1>Liste des articles !!!</h1>
    <ul>
        {% for article in articles %}
            <li>{{ article.titre }} <a href="{% url 'firstapp:details' article.id %}">Voir détail</a></li>
        {% endfor %}
    </ul>

    <h1>Liste des auteurs</h1>
    <form method="post">
        {% csrf_token %}
        <select name="listes_auteur" onchange="this.form.submit()">
            {% for auteur in auteurs %}
                <option value="{{ auteur.id }}" {% if request.session.auteur_selected == auteur.id %}selected{% endif %}>{{ auteur.prenom }} {{ auteur.nom }}</option>
            {% endfor %}
        </select>
    </form>

    <table>
            <tr>
                <th>Titre</th>
                <th>Contenu</th>
                <th>Date de publucation</th>
                <th>Auteur</th>
            </tr>
        </thead>
        <tbody>
            {% for article in articles_filtre %}
                <tr>
                    <td>{{ article.titre }}</td>
                    <td>{{ article.contenu }}</td>
                    <td>{{ article.date_publication|date:"D/M/Y" }}</td>
                    <td>{{ article.auteur.prenom }} {{ article.auteur.nom|upper }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/firstapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
     <title>{% block title %}Mon Site{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <a class="navbar-brand" href="#">Hidden brand</a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'firstapp:articles' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>

</body>
</html>

templates/firstapp/details_articles.html
{% extends "firstapp/base.html" %}

{% block title %}Articles ...{% endblock %}

{% block content %}
    <h1>{{ art.titre }}</h1>
    <p>{{ art.contenu }}</p>
    <p>{{ art.date_publication }}</p>
    {{ art.auteur.prenom}} {{ art.auteur.nom}}
{% endblock %}